# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    role_hierarchy:
        ROLE_SCREEN: ROLE_USER
        ROLE_DYLO:  [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        
    encoders:
        DyloProd\PPSBundle\Entity\Guest: plaintext

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        guest_provider:
            entity:
                class: DyloProdPPSBundle:Guest
                property: username
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        free:
            pattern: ^/(login|gallery)/
            security: false
        main:
            pattern: ^/
            anonymous: ~
            provider: guest_provider
            form_login:
                login_path: /login
                csrf_token_generator: security.csrf.token_manager
            logout:
                path:   /logout
                target: /
                
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    access_control:
        - { path: ^/admin, roles: ROLE_DYLO}
        - { path: ^/gallery, roles: ROLE_SCREEN, ips: [127.0.0.1, ::1] }
        - { path: ^/gallery, roles: ROLE_NO_ACCESS }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }