<?php

namespace DyloProd\PPSBundle\Repository;

use Doctrine\ORM\EntityRepository;
use DyloProd\PPSBundle\Entity\Event;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
    public function findCurrentEvent()
    {
        $dateNow = new \DateTime();
        $em = $this->getEntityManager();
        
        $events = $this->getEntityManager()
                ->createQuery(
                    'SELECT e FROM DyloProdPPSBundle:Event e WHERE e.hDebut < :dateNow AND e.hFin > :dateNow'
                )
                ->setParameter("dateNow",$dateNow)
                ->getResult();
        
        if(!$events)
        {
            $today = new \Datetime("today");
            $tomorrow = new \Datetime("tomorrow");
            
            $jour_str = $this->dateFrench($today);
            
            $event = new Event();
            $event->setTitre("Journée du ".$jour_str);
            $event->setHDebut($today);
            $event->setHFin($tomorrow);
            
            $em->persist($event);
            $em->flush();
            
            //echo "ca passe";
        }
        else {
            $event = $events[0];
        }
        
        return $event;
    }
    
    public function dateFrench($date) 
    {
        $english_days = array('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday');
        $french_days = array('Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi', 'Dimanche');
        $english_months = array('January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December');
        $french_months = array('Janvier', 'Février', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Août', 'Septembre', 'Octobre', 'Novembre', 'Décembre');
        return str_replace($english_months, $french_months, str_replace($english_days, $french_days, $date->format("l d F Y")));
    }
}
